# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personal.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1419, 716)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 470, 131, 16))
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 500, 761, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout.addWidget(self.checkBox_4, 0, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout.addWidget(self.checkBox_5, 1, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout.addWidget(self.checkBox_6, 2, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(680, 620, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(430, 20, 47, 13))
        self.label_45.setObjectName("label_45")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(320, 120, 181, 20))
        self.label_40.setObjectName("label_40")
        self.lineEdit_pass_number_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pass_number_2.setGeometry(QtCore.QRect(510, 50, 113, 20))
        self.lineEdit_pass_number_2.setReadOnly(True)
        self.lineEdit_pass_number_2.setObjectName("lineEdit_pass_number_2")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(50, 70, 61, 16))
        self.label_41.setObjectName("label_41")
        self.lineEdit_name_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_name_2.setGeometry(QtCore.QRect(160, 40, 113, 20))
        self.lineEdit_name_2.setReadOnly(True)
        self.lineEdit_name_2.setObjectName("lineEdit_name_2")
        self.lineEdit_given_by_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_given_by_2.setGeometry(QtCore.QRect(510, 80, 113, 20))
        self.lineEdit_given_by_2.setReadOnly(True)
        self.lineEdit_given_by_2.setObjectName("lineEdit_given_by_2")
        self.lineEdit_given_date_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_given_date_2.setGeometry(QtCore.QRect(510, 160, 113, 20))
        self.lineEdit_given_date_2.setReadOnly(True)
        self.lineEdit_given_date_2.setObjectName("lineEdit_given_date_2")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(330, 390, 47, 13))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(50, 110, 47, 13))
        self.label_37.setObjectName("label_37")
        self.lineEdit_secondname_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_secondname_2.setGeometry(QtCore.QRect(160, 70, 113, 20))
        self.lineEdit_secondname_2.setReadOnly(True)
        self.lineEdit_secondname_2.setObjectName("lineEdit_secondname_2")
        self.lineEdit_place_birth_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_place_birth_2.setGeometry(QtCore.QRect(160, 230, 113, 20))
        self.lineEdit_place_birth_2.setReadOnly(True)
        self.lineEdit_place_birth_2.setObjectName("lineEdit_place_birth_2")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(50, 230, 81, 16))
        self.label_50.setObjectName("label_50")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(50, 10, 47, 13))
        self.label_39.setObjectName("label_39")
        self.lineEdit_adress_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_adress_2.setGeometry(QtCore.QRect(540, 420, 113, 20))
        self.lineEdit_adress_2.setReadOnly(True)
        self.lineEdit_adress_2.setObjectName("lineEdit_adress_2")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(10, 270, 131, 20))
        self.label_38.setObjectName("label_38")
        self.lineEdit_phone_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_phone_2.setGeometry(QtCore.QRect(160, 180, 113, 20))
        self.lineEdit_phone_2.setReadOnly(True)
        self.lineEdit_phone_2.setObjectName("lineEdit_phone_2")
        self.lineEdit_birht_date_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_birht_date_2.setGeometry(QtCore.QRect(160, 140, 113, 20))
        self.lineEdit_birht_date_2.setReadOnly(True)
        self.lineEdit_birht_date_2.setObjectName("lineEdit_birht_date_2")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(10, 140, 151, 20))
        self.label_34.setObjectName("label_34")
        self.lineEdit_index_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_index_2.setGeometry(QtCore.QRect(540, 390, 113, 20))
        self.lineEdit_index_2.setReadOnly(True)
        self.lineEdit_index_2.setObjectName("lineEdit_index_2")
        self.label_49 = QtWidgets.QLabel(self.centralwidget)
        self.label_49.setGeometry(QtCore.QRect(330, 420, 191, 16))
        self.label_49.setObjectName("label_49")
        self.radioButton_hostel_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_hostel_2.setGeometry(QtCore.QRect(170, 270, 82, 17))
        self.radioButton_hostel_2.setText("")
        self.radioButton_hostel_2.setObjectName("radioButton_hostel_2")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(430, 50, 47, 13))
        self.label_44.setObjectName("label_44")
        self.lineEdit_surname_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_surname_2.setGeometry(QtCore.QRect(160, 10, 113, 20))
        self.lineEdit_surname_2.setReadOnly(True)
        self.lineEdit_surname_2.setObjectName("lineEdit_surname_2")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(430, 80, 71, 16))
        self.label_47.setObjectName("label_47")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(50, 180, 91, 16))
        self.label_43.setObjectName("label_43")
        self.lineEdit_email_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email_2.setGeometry(QtCore.QRect(160, 110, 113, 20))
        self.lineEdit_email_2.setReadOnly(True)
        self.lineEdit_email_2.setObjectName("lineEdit_email_2")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(350, 160, 151, 20))
        self.label_35.setObjectName("label_35")
        self.lineEdit_code_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_code_2.setGeometry(QtCore.QRect(510, 120, 113, 20))
        self.lineEdit_code_2.setReadOnly(True)
        self.lineEdit_code_2.setObjectName("lineEdit_code_2")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(60, 40, 47, 13))
        self.label_46.setObjectName("label_46")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(330, 200, 161, 16))
        self.label_42.setObjectName("label_42")
        self.lineEdit_series_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_series_2.setGeometry(QtCore.QRect(510, 10, 113, 20))
        self.lineEdit_series_2.setReadOnly(True)
        self.lineEdit_series_2.setObjectName("lineEdit_series_2")
        self.label_48 = QtWidgets.QLabel(self.centralwidget)
        self.label_48.setGeometry(QtCore.QRect(30, 310, 41, 20))
        self.label_48.setObjectName("label_48")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(1040, 300, 47, 13))
        self.label_54.setObjectName("label_54")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(1020, 70, 61, 16))
        self.label_60.setObjectName("label_60")
        self.label_58 = QtWidgets.QLabel(self.centralwidget)
        self.label_58.setGeometry(QtCore.QRect(1020, 30, 181, 16))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.centralwidget)
        self.label_59.setGeometry(QtCore.QRect(750, 30, 101, 16))
        self.label_59.setObjectName("label_59")
        self.lineEdit_number_of_doc_frame_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_number_of_doc_frame_3.setGeometry(QtCore.QRect(860, 30, 113, 20))
        self.lineEdit_number_of_doc_frame_3.setReadOnly(True)
        self.lineEdit_number_of_doc_frame_3.setObjectName("lineEdit_number_of_doc_frame_3")
        self.label_57 = QtWidgets.QLabel(self.centralwidget)
        self.label_57.setGeometry(QtCore.QRect(750, 70, 81, 16))
        self.label_57.setObjectName("label_57")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(1040, 250, 81, 16))
        self.label_56.setObjectName("label_56")
        self.lineEdit_math_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_math_2.setGeometry(QtCore.QRect(1150, 250, 113, 20))
        self.lineEdit_math_2.setReadOnly(True)
        self.lineEdit_math_2.setObjectName("lineEdit_math_2")
        self.lineEdit_rus_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_rus_2.setGeometry(QtCore.QRect(1150, 290, 113, 20))
        self.lineEdit_rus_2.setReadOnly(True)
        self.lineEdit_rus_2.setObjectName("lineEdit_rus_2")
        self.lineEdit_inf = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_inf.setGeometry(QtCore.QRect(1160, 340, 113, 20))
        self.lineEdit_inf.setReadOnly(True)
        self.lineEdit_inf.setObjectName("lineEdit_inf")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(1040, 340, 121, 16))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.centralwidget)
        self.label_52.setGeometry(QtCore.QRect(740, 290, 81, 16))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.centralwidget)
        self.label_53.setGeometry(QtCore.QRect(740, 240, 91, 16))
        self.label_53.setObjectName("label_53")
        self.lineEdit_fizika = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_fizika.setGeometry(QtCore.QRect(1160, 380, 113, 20))
        self.lineEdit_fizika.setText("")
        self.lineEdit_fizika.setReadOnly(True)
        self.lineEdit_fizika.setObjectName("lineEdit_fizika")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(1040, 380, 121, 16))
        self.label_55.setObjectName("label_55")
        self.lineEdit_achiev = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_achiev.setGeometry(QtCore.QRect(1210, 30, 113, 22))
        self.lineEdit_achiev.setReadOnly(True)
        self.lineEdit_achiev.setObjectName("lineEdit_achiev")
        self.user_photo = QtWidgets.QLabel(self.centralwidget)
        self.user_photo.setGeometry(QtCore.QRect(150, 310, 121, 121))
        self.user_photo.setObjectName("user_photo")
        self.first_page = QtWidgets.QLabel(self.centralwidget)
        self.first_page.setGeometry(QtCore.QRect(510, 210, 121, 121))
        self.first_page.setObjectName("first_page")
        self.lineEdit_teach_form = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_teach_form.setGeometry(QtCore.QRect(850, 240, 113, 22))
        self.lineEdit_teach_form.setReadOnly(True)
        self.lineEdit_teach_form.setObjectName("lineEdit_teach_form")
        self.lineEdit_direction = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_direction.setGeometry(QtCore.QRect(850, 290, 113, 22))
        self.lineEdit_direction.setReadOnly(True)
        self.lineEdit_direction.setObjectName("lineEdit_direction")
        self.document = QtWidgets.QLabel(self.centralwidget)
        self.document.setGeometry(QtCore.QRect(850, 90, 121, 121))
        self.document.setObjectName("document")
        self.personal_achiev = QtWidgets.QLabel(self.centralwidget)
        self.personal_achiev.setGeometry(QtCore.QRect(1120, 80, 121, 121))
        self.personal_achiev.setObjectName("personal_achiev")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1419, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Неверные документы:"))
        self.checkBox.setText(_translate("MainWindow", "Фото на личное дело"))
        self.checkBox_2.setText(_translate("MainWindow", "Паспорт"))
        self.checkBox_3.setText(_translate("MainWindow", "Согласие на ОПД"))
        self.checkBox_4.setText(_translate("MainWindow", "Аттестат"))
        self.checkBox_5.setText(_translate("MainWindow", "Индивидуальные достижения"))
        self.checkBox_6.setText(_translate("MainWindow", "Заявление на зачисление"))
        self.pushButton.setText(_translate("MainWindow", "Отправить"))
        self.label_45.setText(_translate("MainWindow", "Серия"))
        self.label_40.setText(_translate("MainWindow", "код подразделения (***-***)"))
        self.label_41.setText(_translate("MainWindow", "Отчество"))
        self.label_36.setText(_translate("MainWindow", "Индекс"))
        self.label_37.setText(_translate("MainWindow", "email"))
        self.label_50.setText(_translate("MainWindow", "Место рожения"))
        self.label_39.setText(_translate("MainWindow", "Фамилия"))
        self.label_38.setText(_translate("MainWindow", "Нужно ли общежитые"))
        self.label_34.setText(_translate("MainWindow", "Дата рождения (мм-дд-гггг)"))
        self.label_49.setText(_translate("MainWindow", "Адрес(город, улица, дом, квартира)"))
        self.label_44.setText(_translate("MainWindow", "Номер"))
        self.label_47.setText(_translate("MainWindow", "кем выдан"))
        self.label_43.setText(_translate("MainWindow", "Номер телофона"))
        self.label_35.setText(_translate("MainWindow", "Дата выдачи (мм-дд-гггг)"))
        self.label_46.setText(_translate("MainWindow", "Имя"))
        self.label_42.setText(_translate("MainWindow", "фотоскан первой страницы"))
        self.label_48.setText(_translate("MainWindow", "Фото"))
        self.label_54.setText(_translate("MainWindow", "Русский"))
        self.label_60.setText(_translate("MainWindow", "Фото/скан"))
        self.label_58.setText(_translate("MainWindow", "Индивидуальное достижение"))
        self.label_59.setText(_translate("MainWindow", "Номер документа"))
        self.label_57.setText(_translate("MainWindow", "Фото/скан"))
        self.label_56.setText(_translate("MainWindow", "Математика"))
        self.label_51.setText(_translate("MainWindow", "Информатика"))
        self.label_52.setText(_translate("MainWindow", "Направление"))
        self.label_53.setText(_translate("MainWindow", "Форма обучения"))
        self.label_55.setText(_translate("MainWindow", "Физика"))
        self.user_photo.setText(_translate("MainWindow", "Фото"))
        self.first_page.setText(_translate("MainWindow", "Фото"))
        self.document.setText(_translate("MainWindow", "Фото"))
        self.personal_achiev.setText(_translate("MainWindow", "Фото"))
