# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'work_with_app.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_first = QtWidgets.QFrame(self.centralwidget)
        self.frame_first.setGeometry(QtCore.QRect(20, 0, 761, 521))
        self.frame_first.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_first.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_first.setObjectName("frame_first")
        self.lineEdit_surname = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_surname.setGeometry(QtCore.QRect(170, 10, 113, 20))
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.lineEdit_name = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_name.setGeometry(QtCore.QRect(170, 40, 113, 20))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.lineEdit_secondname = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_secondname.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.lineEdit_secondname.setObjectName("lineEdit_secondname")
        self.lineEdit_birht_date = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_birht_date.setGeometry(QtCore.QRect(170, 140, 113, 20))
        self.lineEdit_birht_date.setObjectName("lineEdit_birht_date")
        self.lineEdit_phone = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_phone.setGeometry(QtCore.QRect(170, 180, 113, 20))
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.lineEdit_place_birth = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_place_birth.setGeometry(QtCore.QRect(170, 230, 113, 20))
        self.lineEdit_place_birth.setObjectName("lineEdit_place_birth")
        self.lineEdit_email = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_email.setGeometry(QtCore.QRect(170, 110, 113, 20))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.radioButton_hostel = QtWidgets.QRadioButton(self.frame_first)
        self.radioButton_hostel.setGeometry(QtCore.QRect(180, 270, 82, 17))
        self.radioButton_hostel.setText("")
        self.radioButton_hostel.setObjectName("radioButton_hostel")
        self.lineEdit_photo = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_photo.setGeometry(QtCore.QRect(170, 310, 113, 20))
        self.lineEdit_photo.setObjectName("lineEdit_photo")
        self.pushButton_select_photo = QtWidgets.QPushButton(self.frame_first)
        self.pushButton_select_photo.setGeometry(QtCore.QRect(290, 310, 31, 23))
        self.pushButton_select_photo.setObjectName("pushButton_select_photo")
        self.label = QtWidgets.QLabel(self.frame_first)
        self.label.setGeometry(QtCore.QRect(60, 10, 61, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_first)
        self.label_2.setGeometry(QtCore.QRect(70, 40, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_first)
        self.label_3.setGeometry(QtCore.QRect(60, 70, 61, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_first)
        self.label_4.setGeometry(QtCore.QRect(60, 110, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_first)
        self.label_5.setGeometry(QtCore.QRect(60, 140, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_first)
        self.label_6.setGeometry(QtCore.QRect(60, 180, 111, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_first)
        self.label_7.setGeometry(QtCore.QRect(60, 230, 101, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_first)
        self.label_8.setGeometry(QtCore.QRect(40, 270, 131, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_first)
        self.label_9.setGeometry(QtCore.QRect(40, 310, 131, 20))
        self.label_9.setObjectName("label_9")
        self.lineEdit_series = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_series.setGeometry(QtCore.QRect(520, 10, 113, 20))
        self.lineEdit_series.setObjectName("lineEdit_series")
        self.label_10 = QtWidgets.QLabel(self.frame_first)
        self.label_10.setGeometry(QtCore.QRect(440, 20, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_first)
        self.label_11.setGeometry(QtCore.QRect(440, 50, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_first)
        self.label_12.setGeometry(QtCore.QRect(440, 80, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame_first)
        self.label_13.setGeometry(QtCore.QRect(390, 120, 101, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_first)
        self.label_14.setGeometry(QtCore.QRect(420, 160, 81, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_first)
        self.label_15.setGeometry(QtCore.QRect(370, 190, 161, 16))
        self.label_15.setObjectName("label_15")
        self.lineEdit_pass_number = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_pass_number.setGeometry(QtCore.QRect(520, 50, 113, 20))
        self.lineEdit_pass_number.setObjectName("lineEdit_pass_number")
        self.lineEdit_given_by = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_given_by.setGeometry(QtCore.QRect(520, 80, 113, 20))
        self.lineEdit_given_by.setObjectName("lineEdit_given_by")
        self.lineEdit_code = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_code.setGeometry(QtCore.QRect(520, 120, 113, 20))
        self.lineEdit_code.setObjectName("lineEdit_code")
        self.lineEdit_given_date = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_given_date.setGeometry(QtCore.QRect(520, 160, 113, 20))
        self.lineEdit_given_date.setObjectName("lineEdit_given_date")
        self.lineEdit_photo_passport = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_photo_passport.setGeometry(QtCore.QRect(540, 190, 113, 20))
        self.lineEdit_photo_passport.setObjectName("lineEdit_photo_passport")
        self.pushButton_select_photo_passport = QtWidgets.QPushButton(self.frame_first)
        self.pushButton_select_photo_passport.setGeometry(QtCore.QRect(660, 190, 31, 23))
        self.pushButton_select_photo_passport.setObjectName("pushButton_select_photo_passport")
        self.label_16 = QtWidgets.QLabel(self.frame_first)
        self.label_16.setGeometry(QtCore.QRect(370, 270, 47, 13))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_first)
        self.label_17.setGeometry(QtCore.QRect(370, 300, 221, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_index = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_index.setGeometry(QtCore.QRect(560, 270, 113, 20))
        self.lineEdit_index.setObjectName("lineEdit_index")
        self.lineEdit_adress = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_adress.setGeometry(QtCore.QRect(590, 300, 113, 20))
        self.lineEdit_adress.setObjectName("lineEdit_adress")
        self.pushButton = QtWidgets.QPushButton(self.frame_first)
        self.pushButton.setGeometry(QtCore.QRect(70, 410, 211, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_18 = QtWidgets.QLabel(self.frame_first)
        self.label_18.setGeometry(QtCore.QRect(320, 410, 211, 21))
        self.label_18.setObjectName("label_18")
        self.lineEdit_agreement = QtWidgets.QLineEdit(self.frame_first)
        self.lineEdit_agreement.setGeometry(QtCore.QRect(520, 410, 113, 20))
        self.lineEdit_agreement.setObjectName("lineEdit_agreement")
        self.pushButton_select_photo_passport_select_agreement = QtWidgets.QPushButton(self.frame_first)
        self.pushButton_select_photo_passport_select_agreement.setGeometry(QtCore.QRect(640, 410, 31, 23))
        self.pushButton_select_photo_passport_select_agreement.setObjectName("pushButton_select_photo_passport_select_agreement")
        self.pushButton_next = QtWidgets.QPushButton(self.frame_first)
        self.pushButton_next.setGeometry(QtCore.QRect(550, 480, 121, 23))
        self.pushButton_next.setObjectName("pushButton_next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_select_photo.setText(_translate("MainWindow", "..."))
        self.label.setText(_translate("MainWindow", "Фамилия"))
        self.label_2.setText(_translate("MainWindow", "Имя"))
        self.label_3.setText(_translate("MainWindow", "Отчество"))
        self.label_4.setText(_translate("MainWindow", "email"))
        self.label_5.setText(_translate("MainWindow", "Дата рождения"))
        self.label_6.setText(_translate("MainWindow", "Номер телофона"))
        self.label_7.setText(_translate("MainWindow", "Место рожения"))
        self.label_8.setText(_translate("MainWindow", "Нужно ли общежитые"))
        self.label_9.setText(_translate("MainWindow", "фото на личное дело"))
        self.label_10.setText(_translate("MainWindow", "Серия"))
        self.label_11.setText(_translate("MainWindow", "Номер"))
        self.label_12.setText(_translate("MainWindow", "Кем выдан"))
        self.label_13.setText(_translate("MainWindow", "Код подразделения"))
        self.label_14.setText(_translate("MainWindow", "Дата выдачи"))
        self.label_15.setText(_translate("MainWindow", "Фотоскан первой страницы"))
        self.pushButton_select_photo_passport.setText(_translate("MainWindow", "..."))
        self.label_16.setText(_translate("MainWindow", "Индекс"))
        self.label_17.setText(_translate("MainWindow", "Адрес(город, улица, дом, квартира)"))
        self.pushButton.setText(_translate("MainWindow", "Получить согласие на обработку"))
        self.label_18.setText(_translate("MainWindow", "Загрузить согласие на обработку"))
        self.pushButton_select_photo_passport_select_agreement.setText(_translate("MainWindow", "..."))
        self.pushButton_next.setText(_translate("MainWindow", "Следующий шаг"))
